SELECT *
FROM ACTIVITES

SELECT *
FROM ACTIVITES_PRATIQUEES
WHERE NIVEAU = 1 AND NOM like 'Rugby'

SELECT e.NOM, e.PRENOM
FROM ELEVES e
JOIN ACTIVITES_PRATIQUEES ap ON e.NUM_ELEVE = ap.NUM_ELEVE
JOIN ACTIVITES a ON ap.NOM = a.NOM AND ap.NIVEAU = a.NIVEAU
WHERE a.EQUIPE = 'Equipe 1'

