/* Obtenir le total des points de l'éleve 3 */

SELECT R.NUM_ELEVE, SUM(R.POINTS) SOMME_POINTS
FROM RESULTATS R
JOIN ELEVES E ON E.NUM_ELEVE = R.NUM_ELEVE
WHERE E.NUM_ELEVE = 3
GROUP BY R.NUM_ELEVE