/*
Requête N 26 : Obtenir la moyenne des notes, pour chaque élève
*/

SELECT E.NOM, AVG(CAST(R.POINTS AS FLOAT)) MOY_NOTES
FROM ELEVES E
JOIN RESULTATS R ON R.NUM_ELEVE = E.NUM_ELEVE
GROUP BY E.NOM
ORDER BY AVG(CAST(R.POINTS AS FLOAT)) DESC